mongodata:
  image: mongo:3.0.4
  volumes:
    - /data/db:/data/db
  command: --break-mongo
mongo:
  image: mongo:3.0.4
  volumes_from:
    - mongodata
  ports:
    - "27017:27017"
  command: --smallfiles --rest